### ISSUE TITLE
blob is not defined

### ISSUE THREAD

**Issue by sacrosanctic** [fabian-hiller/valibot#238]
I get an error when trying to validate a blob from a input file, regardless or whether it is empty or not.

```js
import {blob,object} from 'valibot'
import {decode} from 'decode-formdata'

const schema = object({file: blob()})
const data = decode(formData, {files:['file']})
const result = safeParse(schema, data)
```

```bash
ReferenceError: Blob is not defined
     at Object._parse (file:///C:/repo/node_modules/.pnpm/valibot@0.19.0/node_modules/valibot/dist/index.js:570:30)
     at Object._parse (file:///C:/repo/node_modules/.pnpm/valibot@0.19.0/node_modules/valibot/dist/index.js:2130:31)
     at Proxy.safeParse (file:///C:/repo/node_modules/.pnpm/valibot@0.19.0/node_modules/valibot/dist/index.js:3689:25)
     at default (C:/repo/src/routes/+page.server.ts:34:42)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)
     at async Module.handle_action_json_request (C:/repo/node_modules/.pnpm/@sveltejs+kit@1.25.0_svelte@4.2.1_vite@4.4.9/node_modules/@sveltejs/kit/src/runtime/server/page/actions.js:57:16)
     at async resolve (C:/repo/node_modules/.pnpm/@sveltejs+kit@1.25.0_svelte@4.2.1_vite@4.4.9/node_modules/@sveltejs/kit/src/runtime/server/respond.js:415:18)
     at async Object.handle (C:/repo/src/hooks.server.ts:17:10) 
     at async Module.respond (C:/repo/node_modules/.pnpm/@sveltejs+kit@1.25.0_svelte@4.2.1_vite@4.4.9/node_modules/@sveltejs/kit/src/runtime/server/respond.js:282:20)
```

**Comment by fabian-hiller** [comment]
The problem is that your runtime is not aware of `Blob`. Can you describe where and how you execute Valibot? According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Blob#browser_compatibility), `Blob` should by available in all modern browsers as well as in Deno and Node.js. Could it be that you are using an old version of Node.js?

**Comment by sacrosanctic** [comment]
![image](https://github.com/fabian-hiller/valibot/assets/2974920/d6e9f3c0-ca83-46a2-ad21-747689433935)

I am on node16, that is most likely the problem.

Is it possible to set minimum requirements for this package?

**Comment by fabian-hiller** [comment]
Please try to add an polyfill on your own first. But it is a good hint. If that's the problem, we should mention it in our docs once we add the API reference to it.

**Comment by fabian-hiller** [comment]
I will add a note to our source code to document this in the long run.
