### ISSUE TITLE
After latest upgrade problems with validation function

### ISSUE THREAD

**Issue by crystalfp** [fabian-hiller/valibot#262]
After upgrade to valibot 0.21.0 my string pipeline gives errors both at compilation and runtime.
The pipeline is:
```
const projectSchema = object({
	documents: array(object({
		id: string([validateUuidWithSequence]),
	}))
});
```
And the validator, simplified, is:
```
const validateUuidWithSequence = (value: string): PipeResult<string> => {

	if(value.length > 36) {

		const sequence = Number.parseInt(value.slice(37), 16);
		if(Number.isNaN(sequence) || sequence <= 0 || sequence > 0xF_FF) {
			return getPipeIssues("custom", "Invalid fragment sequence", value);
		}
	}
	return getOutput(value);
};
```
This at compilation gives:
```
No overload matches this call.
  Overload 1 of 2, '(pipe?: Pipe<string> | undefined): StringSchema<string>', gave the following error.
    Type '(value: string) => PipeResult<string>' is not assignable to type 'BaseValidation<string> | BaseTransformation<string>'.
  Overload 2 of 2, '(message?: ErrorMessage | undefined, pipe?: Pipe<string> | undefined): StringSchema<string>', gave the following error.
    Argument of type '((value: string) => PipeResult<string>)[]' is not assignable to parameter of type 'ErrorMessage | undefined'.
```
And at runtime (I'm running inside Electron):
```
Error occurred in handler for 'PROJECTS:GET-ALL': TypeError: action._parse is not a function
    at executePipe (D:\Projects\IIE\dist-electron\main.js:14220:27)
    at Object._parse (D:\Projects\IIE\dist-electron\main.js:14488:14)
    at Object._parse (D:\Projects\IIE\dist-electron\main.js:14378:32)
    at Object._parse (D:\Projects\IIE\dist-electron\main.js:14299:34)
    at Object._parse (D:\Projects\IIE\dist-electron\main.js:14378:32)
    at safeParse (D:\Projects\IIE\dist-electron\main.js:14493:26)
    at projectIsValid (D:\Projects\IIE\dist-electron\main.js:14598:18)
```
Everything was working before the update.
Thanks for looking!
mario

**Comment by crystalfp** [comment]
Was too fast, sorry.
Not trying to follow the migration rules in https://github.com/fabian-hiller/valibot/releases/tag/v0.21.0

**Comment by crystalfp** [comment]
If could be helpful to someone, here is the working version:
```
const validateUuidWithSequence = (): BaseValidation<string> => {
	return {
		async: false,
		message: "Invalid UUID with sequence",
		_parse(value: string) {
			if(value.length > 36) {

				const sequence = Number.parseInt(value.slice(37), 16);
				if(Number.isNaN(sequence) || sequence <= 0 || sequence > 0xF_FF) {
					return getPipeIssues("custom", "Invalid fragment sequence", value);
				}
			}
			return getOutput(value);
		},
	};
};
```
And it is called this way:
```
const projectSchema = object({
        documents: array(object({
		id: string([validateUuidWithSequence()]),
	}))
});
```
