### ISSUE TITLE
`maxValue` not working with strings as expected

### ISSUE THREAD

**Issue by brandonpittman** [fabian-hiller/valibot#404]
```ts
  const schema = string([minValue("0"), maxValue("100")]);
  const res = safeParse(schema, "50");

  console.log(res);
```

Produces this error output:

```
{
  typed: true,
  success: false,
  data: '50',
  output: '50',
  error: ValiError: Invalid value
      at Proxy.safeParse (file:///Users/blp/Developer/splink/cq_test_web/node_modules/valibot/dist/index.js:2848:29)
      at Object.useServerTimeLoader_routeLoader_xtRxaSknc8w (/Users/blp/Developer/splink/cq_test_web/packages/app/src/routes/layout.tsx:45:40)
      at Object.invokeApply (/Users/blp/Developer/splink/cq_test_web/node_modules/@builder.io/qwik/core.mjs:4431:26)
      at Object.invoke (/Users/blp/Developer/splink/cq_test_web/node_modules/@builder.io/qwik/core.mjs:4423:24)
      at eval (/Users/blp/Developer/splink/cq_test_web/node_modules/@builder.io/qwik/core.mjs:8497:35)
      at maybeThen (/Users/blp/Developer/splink/cq_test_web/node_modules/@builder.io/qwik/core.mjs:450:56)
      at eval (/Users/blp/Developer/splink/cq_test_web/node_modules/@builder.io/qwik/core.mjs:8483:20)
      at Object.qrl (/Users/blp/Developer/splink/cq_test_web/node_modules/@builder.io/qwik/core.mjs:8444:30)
      at file:///Users/blp/Developer/splink/cq_test_web/node_modules/@builder.io/qwik-city/vite/index.mjs:24470:38
      at measure (file:///Users/blp/Developer/splink/cq_test_web/node_modules/@builder.io/qwik-city/vite/index.mjs:24719:18)
      at file:///Users/blp/Developer/splink/cq_test_web/node_modules/@builder.io/qwik-city/vite/index.mjs:24467:24
      at async Promise.all (index 0)
      at async file:///Users/blp/Developer/splink/cq_test_web/node_modules/@builder.io/qwik-city/vite/index.mjs:24456:7
      at async Object.next (file:///Users/blp/Developer/splink/cq_test_web/node_modules/@builder.io/qwik-city/vite/index.mjs:24840:9)
      at async runNext (file:///Users/blp/Developer/splink/cq_test_web/node_modules/@builder.io/qwik-city/vite/index.mjs:25085:5)
      at async file:///Users/blp/Developer/splink/cq_test_web/node_modules/@builder.io/qwik-city/vite/index.mjs:25653:26 {
    issues: [ [Object] ]
  },
  issues: [
    {
      reason: 'string',
      validation: 'max_value',
      origin: 'value',
      message: 'Invalid value',
      input: '50',
      requirement: '100',
      path: undefined,
      abortEarly: undefined,
      abortPipeEarly: undefined,
      skipPipe: undefined
    }
  ]
}
```

If I use `maxValue("99")`, it works. Do the number of digits need to be the same for this validator to work?

**Comment by fabian-hiller** [comment]
You are comparing strings, not numbers. The string "100" is smaller than the string "50" because "100" starts with "1" and "50" starts with "5". Our implementation is not incorrect. To be able to compare strings reliably, a standardized format such as [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) is required.

**Comment by brandonpittman** [comment]
@fabian-hiller 

This seems to work:

```ts
  const schema = transform(
    coerce(number([minValue(0), maxValue(100)]), Number),
    String
  );
  const res = safeParse(schema, "50");
```

Is this okay or is there a better way of taking a string, running the min/max check and then returning a string?

**Comment by fabian-hiller** [comment]
Yes, this works. An alternative is to add leading zeros.

```ts
import * as v from 'valibot';

const Schema = v.string([
  v.decimal(),
  v.minLength(3),
  v.toCustom((input) => input.padStart(3, '0')),
  v.minValue('0'),
  v.maxValue('100'),
]);
```

**Comment by fabian-hiller** [comment]
> It looks like Modular Forms doesn't like this schema

That's because the input type matters to Modular Forms, and in your example the input type is a number.

It is important to note that Modular Forms can handle numbers. You don't need to use a string.

**Comment by fabian-hiller** [comment]
You could also use `custom` to add custom validation logic:

```ts
import * as v from 'valibot';

const Schema = v.string([
  v.decimal(),
  v.custom((input) => {
    const number = parseInt(input);
    return number >= 0 && number <= 100;
  }),
]);
```

**Comment by fabian-hiller** [comment]
But if it works for you, I would prefer to use a number:

```ts
import * as v from 'valibot';

const Schema = v.number([v.integer(), v.minValue(0), v.maxValue(100)]);
```

**Comment by brandonpittman** [comment]
Thanks. I went with the string/custom solution because there's a bunch of stuff in other components that assume everything's a string. Will refactor to use numbers later. 🥳
